apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: registry.digitalocean.com/krishnaregistry/newpythonapp
        ports:
        - containerPort: 8080 # Make sure this matches the port your app runs on
        imagePullPolicy: Always
